name = "taskmg"
# 互換性の日付は最新のものを指定
compatibility_date = "2025-11-23" 

# [site] セクションは、Workersで静的ファイルをホストするための設定だよ
[site]
# 【重要】変更点: publicではなくViteのビルド成果物ディレクトリ'./dist'を指定
bucket = "./dist"
# Workersで静的ファイルを扱うためのボイラープレートの場所
entry-point = "workers-site"