name = "taskmg"
# 互換性の日付は最新のものを指定
compatibility_date = "2025-11-23" 

# [site] セクションの設定
[site]
# 【修正】Viteのビルド成果物である dist フォルダを参照するように変更
bucket = "./dist"
# Workersで静的ファイルを扱うためのボイラープレートの場所
entry-point = "workers-site"